
#alchitry 100mhz clock
set_property PACKAGE_PIN N14 [get_ports CLK]
set_property IOSTANDARD LVCMOS25 [get_ports CLK]

#alchitry leds
set_property PACKAGE_PIN K13 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[0]]
set_property PACKAGE_PIN K12 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[1]]
set_property PACKAGE_PIN L14 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[2]]
set_property PACKAGE_PIN L13 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[3]]
set_property PACKAGE_PIN M16 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[4]]
set_property PACKAGE_PIN M14 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[5]]
set_property PACKAGE_PIN M12 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[6]]
set_property PACKAGE_PIN N16 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS25 [get_ports LED[7]]


# FT601 USB Signals

set_property PACKAGE_PIN R3 [get_ports USB_BE[0]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_BE[0]]
#FT601 K1 : FT600 H1
set_property PACKAGE_PIN T2 [get_ports USB_BE[1]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_BE[1]]
set_property PACKAGE_PIN R2 [get_ports USB_BE[2]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_BE[2]]
set_property PACKAGE_PIN R1 [get_ports USB_BE[3]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_BE[3]]

set_property PACKAGE_PIN T10 [get_ports USB_DATA[0]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[0]]
set_property PACKAGE_PIN T9 [get_ports USB_DATA[1]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[1]]
set_property PACKAGE_PIN R6 [get_ports USB_DATA[2]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[2]]
set_property PACKAGE_PIN R7 [get_ports USB_DATA[3]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[3]]
set_property PACKAGE_PIN P9 [get_ports USB_DATA[4]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[4]]
set_property PACKAGE_PIN N9 [get_ports USB_DATA[5]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[5]]
set_property PACKAGE_PIN T8 [get_ports USB_DATA[6]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[6]]
set_property PACKAGE_PIN T7 [get_ports USB_DATA[7]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[7]]
set_property PACKAGE_PIN T5 [get_ports USB_DATA[8]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[8]]
set_property PACKAGE_PIN R5 [get_ports USB_DATA[9]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[9]]
set_property PACKAGE_PIN R8 [get_ports USB_DATA[10]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[10]]
set_property PACKAGE_PIN P8 [get_ports USB_DATA[11]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[11]]
set_property PACKAGE_PIN N6 [get_ports USB_DATA[12]] 
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[12]]
set_property PACKAGE_PIN M6 [get_ports USB_DATA[13]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[13]]
set_property PACKAGE_PIN N3 [get_ports USB_DATA[14]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[14]]
set_property PACKAGE_PIN P3 [get_ports USB_DATA[15]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[15]]
set_property PACKAGE_PIN P4 [get_ports USB_DATA[16]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[16]]
set_property PACKAGE_PIN M4 [get_ports USB_DATA[17]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[17]]
set_property PACKAGE_PIN L4 [get_ports USB_DATA[18]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[18]]
set_property PACKAGE_PIN N4 [get_ports USB_DATA[19]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[19]]
set_property PACKAGE_PIN M5 [get_ports USB_DATA[20]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[20]]
set_property PACKAGE_PIN L5 [get_ports USB_DATA[21]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[21]]
set_property PACKAGE_PIN P5 [get_ports USB_DATA[22]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[22]]
set_property PACKAGE_PIN N2 [get_ports USB_DATA[23]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[23]]
set_property PACKAGE_PIN R10 [get_ports USB_DATA[24]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[24]]
set_property PACKAGE_PIN R11 [get_ports USB_DATA[25]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[25]]
set_property PACKAGE_PIN R12 [get_ports USB_DATA[26]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[26]]
set_property PACKAGE_PIN T12 [get_ports USB_DATA[27]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[27]]
set_property PACKAGE_PIN R13 [get_ports USB_DATA[28]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[28]]
set_property PACKAGE_PIN T13 [get_ports USB_DATA[29]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[29]]
set_property PACKAGE_PIN T4 [get_ports USB_DATA[30]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[30]]
set_property PACKAGE_PIN T3 [get_ports USB_DATA[31]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA[31]]

set_property PACKAGE_PIN P10 [get_ports USB_GPIO[0]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_GPIO[0]]
set_property PACKAGE_PIN P11 [get_ports USB_GPIO[1]]
set_property IOSTANDARD LVCMOS25 [get_ports USB_GPIO[1]]

set_property PACKAGE_PIN N13 [get_ports USB_OE_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_OE_N]
set_property PACKAGE_PIN M1 [get_ports USB_RD_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_RD_N]
set_property PACKAGE_PIN P13 [get_ports USB_RESET_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_RESET_N]
set_property PACKAGE_PIN P1 [get_ports USB_RXF_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_RXF_N]
#set_property PACKAGE_PIN N6 [get_ports USB_SIWU_N]
#set_property IOSTANDARD LVCMOS25 [get_ports USB_SIWU_N]
set_property PACKAGE_PIN N1 [get_ports USB_TXE_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_TXE_N]
set_property PACKAGE_PIN N12 [get_ports USB_WAKEUP_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_WAKEUP_N]
set_property PACKAGE_PIN M2 [get_ports USB_WR_N]
set_property IOSTANDARD LVCMOS25 [get_ports USB_WR_N]

set_property PACKAGE_PIN N11 [get_ports USB_DATA_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports USB_DATA_CLK]


#AFE is one indexed and this is zero indexed. I'm sorry

#Channel 1 INVERT!
set_property PACKAGE_PIN K3 [get_ports DATA_P[0]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[0]]
set_property PACKAGE_PIN K2 [get_ports DATA_N[0]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[0]]

#Channel 2
set_property PACKAGE_PIN J5 [get_ports DATA_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[1]]
set_property PACKAGE_PIN J4 [get_ports DATA_N[1]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[1]]

#Channel 3
set_property PACKAGE_PIN C1 [get_ports DATA_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[2]]
set_property PACKAGE_PIN B1 [get_ports DATA_N[2]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[2]]

#Channel 4
set_property PACKAGE_PIN C3 [get_ports DATA_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[3]]
set_property PACKAGE_PIN C2 [get_ports DATA_N[3]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[3]]

#Channel 5
set_property PACKAGE_PIN G5 [get_ports DATA_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[4]]
set_property PACKAGE_PIN G4 [get_ports DATA_N[4]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[4]]

#Channel 6
set_property PACKAGE_PIN F5 [get_ports DATA_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[5]]
set_property PACKAGE_PIN E5 [get_ports DATA_N[5]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[5]]

#Channel 7
set_property PACKAGE_PIN D6 [get_ports DATA_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[6]]
set_property PACKAGE_PIN D5 [get_ports DATA_N[6]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[6]]

#Channel 8
set_property PACKAGE_PIN C7 [get_ports DATA_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_P[7]]
set_property PACKAGE_PIN C6 [get_ports DATA_N[7]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_N[7]]


set_property PACKAGE_PIN D3 [get_ports DCO_N] 
set_property IOSTANDARD LVDS_25 [get_ports DCO_N]
set_property PACKAGE_PIN E3 [get_ports DCO_P] 
set_property IOSTANDARD LVDS_25 [get_ports DCO_P]

set_property PACKAGE_PIN C4 [get_ports FR_N] 
set_property IOSTANDARD LVDS_25 [get_ports FR_N]
set_property PACKAGE_PIN D4 [get_ports FR_P] 
set_property IOSTANDARD LVDS_25 [get_ports FR_P]


set_property PACKAGE_PIN G1 [get_ports GPIO[0]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[0]]
set_property PACKAGE_PIN H2 [get_ports GPIO[1]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[1]]
set_property PACKAGE_PIN H1 [get_ports GPIO[2]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[2]]
set_property PACKAGE_PIN K1 [get_ports GPIO[3]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[3]]
set_property PACKAGE_PIN J1 [get_ports GPIO[4]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[4]]
set_property PACKAGE_PIN L3 [get_ports GPIO[5]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[5]]
set_property PACKAGE_PIN L2 [get_ports GPIO[6]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[6]]
set_property PACKAGE_PIN M15 [get_ports GPIO[7]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[7]]
set_property PACKAGE_PIN D1 [get_ports GPIO[8]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[8]]
set_property PACKAGE_PIN E2 [get_ports GPIO[9]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[9]]
set_property PACKAGE_PIN A2 [get_ports GPIO[10]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[10]]
# B2 not E2!!!! The alchitry footprint has a mistake
set_property PACKAGE_PIN B2 [get_ports GPIO[11]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[11]]
set_property PACKAGE_PIN E1 [get_ports GPIO[12]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[12]]
set_property PACKAGE_PIN F2 [get_ports GPIO[13]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[13]]
set_property PACKAGE_PIN F3 [get_ports GPIO[14]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[14]]
set_property PACKAGE_PIN F4 [get_ports GPIO[15]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[15]]
set_property PACKAGE_PIN A3 [get_ports GPIO[16]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[16]]
set_property PACKAGE_PIN B4 [get_ports GPIO[17]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[17]]
set_property PACKAGE_PIN A4 [get_ports GPIO[18]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[18]]
set_property PACKAGE_PIN A5 [get_ports GPIO[19]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[19]]
set_property PACKAGE_PIN B5 [get_ports GPIO[20]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[20]]
set_property PACKAGE_PIN B6 [get_ports GPIO[21]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[21]]
set_property PACKAGE_PIN A7 [get_ports GPIO[22]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[22]]
set_property PACKAGE_PIN B7 [get_ports GPIO[23]]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO[23]]


set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk_wiz_ft601/inst/clk_in1_clk_wiz_ft601_please_work]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk_wiz_ft601/inst/clk_in1_clk_wiz_ft601_please_work_diff_deg]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk_wiz_ft601/inst/clk_in1_clk_wiz_ft601_please_work_diff_deg_1]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets my_ft601_clk_adj/my_adj_ft601_clk/inst/clk_in1_clk_wiz_ft601_adj]


#named GPIO signals
set_property PACKAGE_PIN R16 [get_ports MISO] 
set_property IOSTANDARD LVCMOS25 [get_ports MISO]
set_property PACKAGE_PIN R15 [get_ports MOSI] 
set_property IOSTANDARD LVCMOS25 [get_ports MOSI]
set_property PACKAGE_PIN T14 [get_ports CS_N] 
set_property IOSTANDARD LVCMOS25 [get_ports RESET_IN]
set_property PACKAGE_PIN P14 [get_ports SCLK] 
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]
set_property PACKAGE_PIN T15 [get_ports TRIGGER_IN] 
set_property IOSTANDARD LVCMOS25 [get_ports TRIGGER_IN]